name: Consume_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.GooglePubSub.Consume/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.GooglePubSub.Consume
      prebuild_command: "docker-compose -f Frends.GooglePubSub.Consume.Tests/docker-compose.yml up -d"
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      