name: Frends.GooglePubSub.Publish Main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.GooglePubSub.Publish/**'
  workflow_dispatch:
  
jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_main.yml@main
    with:
      workdir: Frends.GooglePubSub.Publish
      prebuild_command: "docker-compose -f Frends.GooglePubSub.Publish.Tests/docker-compose.yml up -d"
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}