name: Frends.GooglePubSub.Publish Test

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'Frends.GooglePubSub.Publish/**'
  workflow_dispatch:
  

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.GooglePubSub.Publish
      prebuild_command: "docker-compose -f Frends.GooglePubSub.Publish.Tests/docker-compose.yml up -d"
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}